### ISSUE TITLE
创建项目的时候报错了

### ISSUE THREAD

**Issue by yingnierxiao** [cocos-creator/creator-lua#6]
<img width="925" alt="qq20161210-0 2x" src="https://cloud.githubusercontent.com/assets/3435706/21073420/6505ecca-bf18-11e6-93aa-2df1a2a4bdea.png">

**Comment by dualface** [comment]
哪个版本的 creator ？

**Comment by yingnierxiao** [comment]
1.3.2

**Comment by anguskwan** [comment]
+1, 发布到lua project的时候出现的错误，lua support面板里没build成功。在creator里直接运行是没问题的。

creator: 1.3.2，cocos2d-x-3.13.1，win10
==================================
Compiling scripts...
Compiled successfully
1.3.2
  TypeError: Cannot read property 'send' of undefined
at Editor.App.spawnWorker (C:\Users\xxxxx\.CocosCreator\packages\creator-lua-support\main.js:41:15)
at WebContents.<anonymous> (C:\CocosCreator\resources\app.asar\editor\init.js:1:9960)
at emitOne (events.js:101:20)
at WebContents.emit (events.js:188:7)
at process.<anonymous> (C:\CocosCreator\resources\app.asar\editor\core\editor-init.js:1:199)
at emitOne (events.js:101:20)
at process.emit (events.js:188:7)
at process._fatalException (bootstrap_node.js:262:26)

**Comment by anguskwan** [comment]
在win、mac平台下都测试了，1.3.2遇到send undefined的问题，1.4测试版遇到无法设置project path的问题，下载了1.3.0，通过了。

**Comment by yingnierxiao** [comment]
感觉现在lua被边缘化了，  没啥人在用了，准备上u3d了

**Comment by xlambda** [comment]
@anguskwan 在哪里可以下载1.3.0版本？我在官网只看到1.2.2 。

**Comment by anguskwan** [comment]
@xlambda http://cocos2d-x.org/filedown/CocosCreator_v1.3.0_win
改下后缀就可以了

**Comment by dualface** [comment]
看来是 creator 升级后导致插件不兼容了。我尽快修复此问题。谢谢大家！

**Comment by anguskwan** [comment]
@dualface 期待 ：）

**Comment by dualface** [comment]
fixed
