### ISSUE TITLE
1.1.4遇到uuid为空的问题

### ISSUE THREAD

**Issue by anguskwan** [cocos-creator/creator-lua#7]
https://github.com/cocos-creator/creator-lua/releases/tag/1.1.4

操作还原：
1. 在层级管理器里添加ui节点，随便修改点属性
2. 把这个节点拖到资源管理器里，生成prefab
3. build，会出现uuid为空的错误

![image](https://cloud.githubusercontent.com/assets/1006912/21516353/50acdf24-cd12-11e6-8859-28e2b900db3e.png)

···
TypeError: Cannot read property 'uuid' of null
at BuildWorker._parseMeta (C:\Users\an3us-sb\.CocosCreator\packages\creator-lua-support\core\BuildWorker.js:198:24)
at BuildWorker._parseUuid (C:\Users\an3us-sb\.CocosCreator\packages\creator-lua-support\core\BuildWorker.js:194:14)
at BuildWorker._parseProps (C:\Users\an3us-sb\.CocosCreator\packages\creator-lua-support\core\BuildWorker.js:316:22)
at props.forEach (C:\Users\an3us-sb\.CocosCreator\packages\creator-lua-support\core\BuildWorker.js:229:22)
at Array.forEach (native)
at BuildWorker._parseProps (C:\Users\an3us-sb\.CocosCreator\packages\creator-lua-support\core\BuildWorker.js:228:19)
at BuildWorker._parseMeta (C:\Users\an3us-sb\.CocosCreator\packages\creator-lua-support\core\BuildWorker.js:222:18)
at BuildWorker._parseUuid (C:\Users\an3us-sb\.CocosCreator\packages\creator-lua-support\core\BuildWorker.js:194:14)
at BuildWorker._parseProps (C:\Users\an3us-sb\.CocosCreator\packages\creator-lua-support\core\BuildWorker.js:316:22)
at props.forEach (C:\Users\an3us-sb\.CocosCreator\packages\creator-lua-support\core\BuildWorker.js:229:22)
···

**Comment by dualface** [comment]
fixed
